# Generated by Django 4.1.3 on 2022-12-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_account_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(
                help_text="In game name.", max_length=256, unique=True
            ),
        ),
    ]
