# Generated by Django 4.1.3 on 2022-12-06 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_account_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="icon",
        ),
    ]
