# Generated by Django 4.1.3 on 2022-12-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_remove_account_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petownership",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
