# Generated by Django 4.1.4 on 2022-12-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_delete_petownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="col_logs",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
