# Generated by Django 4.1.4 on 2023-01-16 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0011_account_combat_achievement_tier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="col_logs",
        ),
        migrations.RemoveField(
            model_name="account",
            name="combat_achievement_tier",
        ),
    ]
