# Generated by Django 4.1.4 on 2023-02-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_account_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='active',
            new_name='is_active',
        ),
    ]
