# Generated by Django 4.1.4 on 2023-04-24 21:29

from django.db import migrations, models
import django.db.models.deletion
import um.functions


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_active_account_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=128)),
                ('accepted', models.BooleanField(null=True)),
                ('proof', models.ImageField(upload_to=um.functions.get_file_path)),
                ('phrase', models.CharField(max_length=128)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
    ]
