# Generated by Django 4.1.4 on 2023-04-25 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_accountcreationsubmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountCreationSubmission',
            new_name='UserCreationSubmission',
        ),
    ]
