# Generated by Django 4.1.9 on 2023-08-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0016_rename_accountcreationsubmission_usercreationsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_alt",
            field=models.BooleanField(
                default=False,
                help_text="Check if this is an alt account. Doesn't affect anything on the site; used only for helping admins.",
            ),
        ),
    ]
