# Generated by Django 4.1.9 on 2023-10-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0017_account_is_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                help_text="Preferred name to display on website.",
                max_length=256,
            ),
        ),
    ]
