# Generated by Django 4.2.9 on 2024-02-16 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0018_account_preferred_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_alt",
        ),
    ]
