# Generated by Django 4.2.15 on 2024-08-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_remove_account_is_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="discord_id",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
