# Generated by Django 4.2.15 on 2024-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_populate_discord_id_20240818_2331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="discord_id",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
