# Generated by Django 5.2.12 on 2026-09-29 18:09

from django.contrib.auth.hashers import identify_hasher, make_password
from django.db import migrations, models


def hash_plaintext_passwords(apps, schema_editor):
    UserCreationSubmission = apps.get_model("account", "UserCreationSubmission")
    for submission in UserCreationSubmission.objects.all():
        try:
            identify_hasher(submission.password)
        except ValueError:
            submission.password = make_password(submission.password)
            submission.save(update_fields=["password"])


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_alter_account_discord_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercreationsubmission",
            name="password",
            field=models.CharField(
                help_text="Hashed with make_password, never plaintext.", max_length=128
            ),
        ),
        migrations.RunPython(hash_plaintext_passwords, migrations.RunPython.noop),
    ]
