# Generated by Django 4.1.4 on 2023-02-14 19:40

from django.db import migrations


def forwards(apps, schema_data):
    record_submissions = apps.get_model("main", "RecordSubmission")
    pet_submissions = apps.get_model("main", "PetSubmission")
    col_logs_submissions = apps.get_model("main", "ColLogSubmission")
    ca_submissions = apps.get_model("main", "CASubmission")

    new_record_submissions = apps.get_model("achievements", "RecordSubmission")
    new_pet_submissions = apps.get_model("achievements", "PetSubmission")
    new_col_logs_submissions = apps.get_model("achievements", "ColLogSubmission")
    new_ca_submissions = apps.get_model("achievements", "CASubmission")

    base_fields = [
        "proof",
        "notes",
        "date",
        "accepted",
    ]

    for submission in record_submissions.objects.all():
        obj = new_record_submissions.objects.create(
            **{field: getattr(submission, field) for field in base_fields},
            board=submission.board,
            value=submission.value
        )
        obj.accounts.add(*list(submission.accounts.all()))

    for submission in pet_submissions.objects.all():
        new_pet_submissions.objects.create(
            **{field: getattr(submission, field) for field in base_fields},
            account=submission.account,
            pet=submission.pet
        )

    for submission in col_logs_submissions.objects.all():
        new_col_logs_submissions.objects.create(
            **{field: getattr(submission, field) for field in base_fields},
            account=submission.account,
            col_logs=submission.col_logs
        )

    for submission in ca_submissions.objects.all():
        new_ca_submissions.objects.create(
            **{field: getattr(submission, field) for field in base_fields},
            account=submission.account,
            ca_tier=submission.ca_tier
        )


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
