# Generated by Django 4.2.6 on 2023-11-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0009_populate_polymorphic_ctype_id_20231027_1835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casubmission",
            name="ca_tier",
            field=models.IntegerField(
                choices=[(0, "Grandmaster"), (1, "Master"), (2, "Elite")],
                default=1,
                verbose_name="Combat Achievement Tier",
            ),
            preserve_default=False,
        ),
    ]
