# Generated by Django 4.2.6 on 2023-11-29 03:27

from django.db import migrations, models
import um.functions


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0010_alter_casubmission_ca_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basesubmission",
            name="proof",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image as proof for this submission.",
                null=True,
                upload_to=um.functions.get_file_path,
            ),
        ),
    ]
