# Generated by Django 4.2.8 on 2023-12-15 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0011_alter_basesubmission_proof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collogsubmission",
            name="col_logs",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1488),
                ]
            ),
        ),
    ]
