# Generated by Django 4.2.6 on 2024-01-17 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0012_alter_collogsubmission_col_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collogsubmission",
            name="col_logs",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1443),
                ]
            ),
        ),
    ]
