# Generated by Django 4.2.9 on 2024-01-25 19:15

from django.db import migrations, models
import um.functions


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0013_alter_collogsubmission_col_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basesubmission",
            name="proof",
            field=models.ImageField(
                blank=True, null=True, upload_to=um.functions.get_file_path
            ),
        ),
    ]
