# Generated by Django 4.2.9 on 2024-01-26 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0018_account_preferred_name"),
        ("main", "0095_content_has_hiscores_alter_content_hiscores_name"),
        ("achievements", "0014_alter_basesubmission_proof"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hiscores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kill_count", models.IntegerField(default=0)),
                ("rank_overall", models.IntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hiscores",
                        to="account.account",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.content"
                    ),
                ),
            ],
        ),
    ]
