# Generated by Django 4.2.9 on 2024-02-02 18:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0015_hiscores"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hiscores",
            options={
                "ordering": ["-kill_count", "rank_overall"],
                "verbose_name": "Hiscores",
                "verbose_name_plural": "Hiscores",
            },
        ),
    ]
