# Generated by Django 4.2.9 on 2024-02-16 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0102_alter_content_can_be_mentored_and_more"),
        ("account", "0019_remove_account_is_alt"),
        ("achievements", "0016_alter_hiscores_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="hiscores",
            unique_together={("account", "content")},
        ),
    ]
