# Generated by Django 4.2.9 on 2024-04-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0017_alter_hiscores_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordsubmission",
            name="bounty_accepted",
            field=models.BooleanField(
                default=False,
                help_text="For record submissions which are made during a Bounty event for the selected Bounty's content. Must be set to true for a submission to be accepted for a given Bounty event.",
                null=True,
            ),
        ),
    ]
