# Generated by Django 4.2.9 on 2024-06-24 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0018_recordsubmission_bounty_accepted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hiscores",
            options={
                "ordering": ["-score", "rank_overall"],
                "verbose_name": "Hiscores",
                "verbose_name_plural": "Hiscores",
            },
        ),
        migrations.RenameField(
            model_name="hiscores",
            old_name="kill_count",
            new_name="score",
        ),
        migrations.AlterField(
            model_name="collogsubmission",
            name="col_logs",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1521),
                ]
            ),
        ),
    ]
