# Generated by Django 5.2.6 on 2026-02-25 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0019_alter_hiscores_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collogsubmission",
            name="col_logs",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1609),
                ]
            ),
        ),
    ]
