# Generated by Django 4.1.9 on 2023-10-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bounty", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bounty",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AddField(
            model_name="bounty",
            name="prize_pool",
            field=models.PositiveIntegerField(
                default=0, help_text="Total amount of gp in the prize pool."
            ),
        ),
    ]
