# Generated by Django 4.2.6 on 2023-11-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bounty", "0002_alter_bounty_options_bounty_prize_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="title",
            field=models.CharField(default="", max_length=128),
        ),
    ]
