# Generated by Django 4.2.9 on 2024-06-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bounty", "0003_bounty_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="bounty_reason",
            field=models.TextField(
                default="",
                help_text="Give a fun reason for why this npc has a bounty placed on their head!",
                max_length=128,
            ),
            preserve_default=False,
        ),
    ]
