# Generated by Django 4.2.9 on 2024-06-26 18:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bounty", "0004_bounty_bounty_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraBountyReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reward", models.CharField(max_length=32)),
                ("rules", models.TextField(max_length=256)),
                (
                    "percent_of_prize_pool",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "bounty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bounty.bounty"
                    ),
                ),
            ],
        ),
    ]
