# Generated by Django 4.2.9 on 2024-06-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bounty", "0005_extrabountyreward"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="event_phrase",
            field=models.CharField(default="DARN TOOTIN", max_length=32),
            preserve_default=False,
        ),
    ]
