# Generated by Django 4.2.9 on 2024-06-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bounty", "0006_bounty_event_phrase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrabountyreward",
            name="bounty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_rewards",
                to="bounty.bounty",
            ),
        ),
    ]
