# Generated by Django 4.2.9 on 2024-06-27 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0019_remove_account_is_alt"),
        ("bounty", "0007_alter_extrabountyreward_bounty"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="first_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="first_place_bounties",
                to="account.account",
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="second_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="second_place_bounties",
                to="account.account",
            ),
        ),
        migrations.AddField(
            model_name="bounty",
            name="third_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="third_place_bounties",
                to="account.account",
            ),
        ),
        migrations.AddField(
            model_name="extrabountyreward",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extra_bounty_rewards",
                to="account.account",
            ),
        ),
    ]
