# Generated by Django 4.2.15 on 2024-08-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bounty", "0008_bounty_first_place_bounty_second_place_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bounty",
            name="enemy_description",
            field=models.CharField(
                default="",
                help_text="Give a fun descriptor for what this npc is! A 'nefarious criminal'? Maybe a 'nasty bug'?",
                max_length=128,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bounty",
            name="bounty_reason",
            field=models.TextField(
                help_text="Give a fun reason for why this npc has a bounty placed on their head!",
                max_length=256,
            ),
        ),
    ]
