# Generated by Django 4.1.4 on 2023-02-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonstone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dragonstonebasesubmission',
            options={'ordering': [models.OrderBy(models.F('date'), descending=True, nulls_last=True)], 'verbose_name': 'Dragonstone Base Submission', 'verbose_name_plural': 'All Dragonstone Submissions'},
        ),
    ]
