# Generated by Django 4.1.4 on 2023-02-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0012_remove_account_col_logs_and_more"),
        ("dragonstone", "0003_alter_sotmsubmission_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsubmission",
            name="donors",
            field=models.ManyToManyField(
                blank=True, related_name="events_donated", to="account.account"
            ),
        ),
        migrations.AlterField(
            model_name="eventsubmission",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="events_participated", to="account.account"
            ),
        ),
        migrations.AlterField(
            model_name="eventsubmission",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "PVM"),
                    (1, "Skilling"),
                    (4, "Mentor"),
                    (2, "Major Event"),
                    (3, "Other"),
                ]
            ),
        ),
    ]
