# Generated by Django 4.1.4 on 2023-02-22 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dragonstone", "0004_alter_eventsubmission_donors_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recruitmentsubmission",
            options={
                "verbose_name": "Recruitment Submission (Staff Only)",
                "verbose_name_plural": "Recruitment Submissions (Staff Only)",
            },
        ),
        migrations.AlterModelOptions(
            name="sotmsubmission",
            options={
                "verbose_name": "Skill of the Month Submission (Staff Only)",
                "verbose_name_plural": "Skill of the Month Submissions (Staff Only)",
            },
        ),
    ]
