# Generated by Django 4.1.4 on 2023-02-22 21:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_active_account_is_active'),
        ('dragonstone', '0005_alter_recruitmentsubmission_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeformSubmission',
            fields=[
                ('dragonstonebasesubmission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dragonstone.dragonstonebasesubmission')),
                ('dragonstone_pts', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeform_dragonstone_pts', to='account.account')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account')),
            ],
            options={
                'verbose_name': 'Freeform Dragonstone Points (Staff Only)',
                'verbose_name_plural': 'Freeform Dragonstone Points (Staff Only)',
            },
            bases=('dragonstone.dragonstonebasesubmission',),
        ),
    ]
