# Generated by Django 4.1.4 on 2023-03-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0014_rename_active_account_is_active"),
        ("dragonstone", "0009_dragonstonebasesubmission_denial_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsubmission",
            name="hosts",
            field=models.ManyToManyField(
                blank=True, related_name="events_hosted", to="account.account"
            ),
        ),
    ]
