# Generated by Django 4.2.6 on 2023-11-01 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dragonstone", "0014_new_dstone_system_20231031_0253"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventsubmission",
            old_name="_donors",
            new_name="temp_donors",
        ),
        migrations.RenameField(
            model_name="eventsubmission",
            old_name="_hosts",
            new_name="temp_hosts",
        ),
        migrations.RenameField(
            model_name="eventsubmission",
            old_name="_participants",
            new_name="temp_participants",
        ),
        migrations.RenameField(
            model_name="mentorsubmission",
            old_name="_mentors",
            new_name="temp_mentors",
        ),
        migrations.RenameField(
            model_name="pvmsplitsubmission",
            old_name="_accounts",
            new_name="temp_accounts",
        ),
        migrations.RemoveField(
            model_name="eventsubmission",
            name="donors",
        ),
        migrations.RemoveField(
            model_name="eventsubmission",
            name="hosts",
        ),
        migrations.RemoveField(
            model_name="eventsubmission",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="mentorsubmission",
            name="mentors",
        ),
        migrations.RemoveField(
            model_name="pvmsplitsubmission",
            name="accounts",
        ),
    ]
