# Generated by Django 4.2.6 on 2023-11-01 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dragonstone", "0015_rename__donors_eventsubmission_temp_donors_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventsubmission",
            old_name="temp_donors",
            new_name="donors",
        ),
        migrations.RenameField(
            model_name="eventsubmission",
            old_name="temp_hosts",
            new_name="hosts",
        ),
        migrations.RenameField(
            model_name="eventsubmission",
            old_name="temp_participants",
            new_name="participants",
        ),
        migrations.RenameField(
            model_name="mentorsubmission",
            old_name="temp_mentors",
            new_name="mentors",
        ),
        migrations.RenameField(
            model_name="pvmsplitsubmission",
            old_name="temp_accounts",
            new_name="accounts",
        ),
    ]
