# Generated by Django 4.2.6 on 2023-11-01 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dragonstone", "0016_rename_temp_donors_eventsubmission_donors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruitmentsubmission",
            name="dragonstonebasesubmission_ptr",
        ),
        migrations.RemoveField(
            model_name="recruitmentsubmission",
            name="recruited",
        ),
        migrations.RemoveField(
            model_name="recruitmentsubmission",
            name="recruiter",
        ),
        migrations.RemoveField(
            model_name="sotmsubmission",
            name="account",
        ),
        migrations.RemoveField(
            model_name="sotmsubmission",
            name="dragonstonebasesubmission_ptr",
        ),
        migrations.DeleteModel(
            name="FreeformSubmission",
        ),
        migrations.DeleteModel(
            name="RecruitmentSubmission",
        ),
        migrations.DeleteModel(
            name="SotMSubmission",
        ),
    ]
