# Generated by Django 4.2.6 on 2023-11-01 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dragonstone",
            "0017_remove_recruitmentsubmission_dragonstonebasesubmission_ptr_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventdonorpoints",
            options={
                "verbose_name": "Event Donor Points",
                "verbose_name_plural": "Event Donor Points",
            },
        ),
        migrations.AlterModelOptions(
            name="eventhostpoints",
            options={
                "verbose_name": "Event Host Points",
                "verbose_name_plural": "Event Host Points",
            },
        ),
        migrations.AlterModelOptions(
            name="eventparticipantpoints",
            options={
                "verbose_name": "Event Participant Points",
                "verbose_name_plural": "Event Participant Points",
            },
        ),
        migrations.AlterModelOptions(
            name="freeformpoints",
            options={
                "verbose_name": "Freeform Points",
                "verbose_name_plural": "Freeform Points",
            },
        ),
        migrations.AlterModelOptions(
            name="mentorpoints",
            options={
                "verbose_name": "Mentor Points",
                "verbose_name_plural": "Mentor Points",
            },
        ),
        migrations.AlterModelOptions(
            name="pvmsplitpoints",
            options={
                "verbose_name": "PVM Split Points",
                "verbose_name_plural": "PVM Split Points",
            },
        ),
        migrations.AlterModelOptions(
            name="recruitmentpoints",
            options={
                "verbose_name": "Recruitment Points",
                "verbose_name_plural": "Recruitment Points",
            },
        ),
        migrations.AlterModelOptions(
            name="sotmpoints",
            options={
                "verbose_name": "Skill of the Month Points",
                "verbose_name_plural": "Skill of the Month Points",
            },
        ),
    ]
