# Generated by Django 4.2.6 on 2023-11-02 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0018_account_preferred_name"),
        ("main", "0069_delete_settings"),
        ("dragonstone", "0019_auto_20231101_1958"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewMemberRaidPoints",
            fields=[
                (
                    "dragonstonepoints_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dragonstone.dragonstonepoints",
                    ),
                ),
            ],
            options={
                "verbose_name": "New Member Raid Points",
                "verbose_name_plural": "New Member Raid Points",
            },
            bases=("dragonstone.dragonstonepoints",),
        ),
        migrations.AlterField(
            model_name="eventsubmission",
            name="donors",
            field=models.ManyToManyField(
                blank=True,
                related_name="event_donors_submissions",
                through="dragonstone.EventDonorPoints",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="eventsubmission",
            name="hosts",
            field=models.ManyToManyField(
                blank=True,
                related_name="event_hosts_submissions",
                through="dragonstone.EventHostPoints",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="eventsubmission",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="event_participants_submissions",
                through="dragonstone.EventParticipantPoints",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="mentorsubmission",
            name="learners",
            field=models.ManyToManyField(
                related_name="mentor_learner_submissions", to="account.account"
            ),
        ),
        migrations.AlterField(
            model_name="mentorsubmission",
            name="mentors",
            field=models.ManyToManyField(
                related_name="mentor_mentor_submissions",
                through="dragonstone.MentorPoints",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="pvmsplitsubmission",
            name="accounts",
            field=models.ManyToManyField(
                related_name="pvm_split_submissions",
                through="dragonstone.PVMSplitPoints",
                to="account.account",
            ),
        ),
        migrations.CreateModel(
            name="NewMemberRaidSubmission",
            fields=[
                (
                    "dragonstonebasesubmission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dragonstone.dragonstonebasesubmission",
                    ),
                ),
                (
                    "accounts",
                    models.ManyToManyField(
                        related_name="new_member_raid_submissions",
                        through="dragonstone.NewMemberRaidPoints",
                        to="account.account",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.content"
                    ),
                ),
                (
                    "new_members",
                    models.ManyToManyField(
                        related_name="new_member_raid_new_member_submissions",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "New Member Raid",
                "verbose_name_plural": "New Member Raids",
            },
            bases=("dragonstone.dragonstonebasesubmission",),
        ),
        migrations.AddField(
            model_name="newmemberraidpoints",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dragonstone.newmemberraidsubmission",
            ),
        ),
    ]
