# Generated by Django 4.2.9 on 2024-01-25 19:15

from django.db import migrations, models
import um.functions


class Migration(migrations.Migration):
    dependencies = [
        ("dragonstone", "0021_alter_dragonstonebasesubmission_proof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dragonstonebasesubmission",
            name="proof",
            field=models.ImageField(
                blank=True, null=True, upload_to=um.functions.get_file_path
            ),
        ),
    ]
