# Generated by Django 4.2.9 on 2024-02-16 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dragonstone", "0022_alter_dragonstonebasesubmission_proof"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dragonstonepoints",
            options={
                "verbose_name": "Dragonstone Points",
                "verbose_name_plural": "All Dragonstone Points",
            },
        ),
    ]
