# Generated by Django 4.2.9 on 2024-03-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dragonstone", "0023_alter_dragonstonepoints_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdonorpoints",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donor_points",
                to="dragonstone.eventsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="eventhostpoints",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="host_points",
                to="dragonstone.eventsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="eventparticipantpoints",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant_points",
                to="dragonstone.eventsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="mentorpoints",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentor_points",
                to="dragonstone.mentorsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="newmemberraidpoints",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points",
                to="dragonstone.newmemberraidsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="pvmsplitpoints",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points",
                to="dragonstone.pvmsplitsubmission",
            ),
        ),
    ]
