# Generated by Django 4.2.9 on 2024-03-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dragonstone", "0024_alter_eventdonorpoints_submission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sotmpoints",
            name="skill",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Attack"),
                    (1, "Defence"),
                    (2, "Strength"),
                    (3, "Hitpoints"),
                    (4, "Ranged"),
                    (5, "Prayer"),
                    (6, "Magic"),
                    (7, "Cooking"),
                    (8, "Woodcutting"),
                    (9, "Fletching"),
                    (10, "Fishing"),
                    (11, "Firemaking"),
                    (12, "Crafting"),
                    (13, "Smithing"),
                    (14, "Mining"),
                    (15, "Herblore"),
                    (16, "Agility"),
                    (17, "Thieving"),
                    (18, "Slayer"),
                    (19, "Farming"),
                    (20, "Runecrafting"),
                    (21, "Hunter"),
                    (22, "Construction"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
