# Generated by Django 4.2.15 on 2024-09-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_alter_account_discord_id"),
        ("dragonstone", "0025_sotmpoints_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorsubmission",
            name="learners",
            field=models.ManyToManyField(
                blank=True,
                related_name="mentor_learner_submissions",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="newmemberraidsubmission",
            name="new_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="new_member_raid_new_member_submissions",
                to="account.account",
            ),
        ),
    ]
