# Generated by Django 4.2.15 on 2024-10-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_alter_account_discord_id"),
        ("main", "0106_alter_settings_options_alter_settings_value"),
        ("dragonstone", "0026_alter_mentorsubmission_learners_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupCAPoints",
            fields=[
                (
                    "dragonstonepoints_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dragonstone.dragonstonepoints",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group CA Points",
                "verbose_name_plural": "Group CA Points",
            },
            bases=("dragonstone.dragonstonepoints",),
        ),
        migrations.CreateModel(
            name="GroupCASubmission",
            fields=[
                (
                    "dragonstonebasesubmission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dragonstone.dragonstonebasesubmission",
                    ),
                ),
                (
                    "ca_tier",
                    models.IntegerField(
                        choices=[(0, "Grandmaster"), (1, "Master"), (2, "Elite")],
                        verbose_name="Combat Achievement Tier",
                    ),
                ),
                (
                    "accounts",
                    models.ManyToManyField(
                        related_name="group_ca_submissions",
                        through="dragonstone.GroupCAPoints",
                        to="account.account",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.content"
                    ),
                ),
            ],
            options={
                "verbose_name": "Group CA Submission",
                "verbose_name_plural": "Group CA Submissions",
            },
            bases=("dragonstone.dragonstonebasesubmission",),
        ),
        migrations.AddField(
            model_name="groupcapoints",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points",
                to="dragonstone.groupcasubmission",
            ),
        ),
    ]
