# Generated by Django 5.2.6 on 2026-02-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dragonstone", "0027_groupcapoints_groupcasubmission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sotmpoints",
            name="skill",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Attack"),
                    (1, "Defence"),
                    (2, "Strength"),
                    (3, "Hitpoints"),
                    (4, "Ranged"),
                    (5, "Prayer"),
                    (6, "Magic"),
                    (7, "Cooking"),
                    (8, "Woodcutting"),
                    (9, "Fletching"),
                    (10, "Fishing"),
                    (11, "Firemaking"),
                    (12, "Crafting"),
                    (13, "Smithing"),
                    (14, "Mining"),
                    (15, "Herblore"),
                    (16, "Agility"),
                    (17, "Thieving"),
                    (18, "Slayer"),
                    (19, "Farming"),
                    (20, "Runecrafting"),
                    (21, "Hunter"),
                    (22, "Construction"),
                    (23, "Sailing"),
                ]
            ),
        ),
    ]
