# Generated by Django 4.1.3 on 2022-12-01 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_boardcategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardcategory",
            options={
                "verbose_name": "Board Category",
                "verbose_name_plural": "Board Categories",
            },
        ),
        migrations.AddField(
            model_name="board",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.boardcategory",
            ),
            preserve_default=False,
        ),
    ]
