# Generated by Django 4.1.3 on 2022-12-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_boardcategory_options_board_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boardcategory',
            name='slug',
            field=models.SlugField(default='temp'),
            preserve_default=False,
        ),
    ]
