# Generated by Django 4.1.3 on 2022-12-02 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_board_slug_boardcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="main.boardcategory",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="main.board",
            ),
        ),
    ]
