# Generated by Django 4.1.3 on 2022-12-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_pet"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="board/icons/"),
        ),
        migrations.AddField(
            model_name="submission",
            name="proof",
            field=models.ImageField(
                blank=True, null=True, upload_to="submission/proof/"
            ),
        ),
    ]
