# Generated by Django 4.1.3 on 2022-12-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_board_icon_submission_proof"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="pet/icons/"),
        ),
    ]
