# Generated by Django 4.1.3 on 2022-12-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_submission_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='user',
            new_name='account',
        ),
    ]
