# Generated by Django 4.1.3 on 2022-12-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_user_submission_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcategory',
            name='slug',
            field=models.SlugField(default='temp'),
            preserve_default=False,
        ),
    ]
