# Generated by Django 4.1.3 on 2022-12-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_boardcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
