# Generated by Django 4.1.3 on 2022-12-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_pet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
