# Generated by Django 4.1.3 on 2022-12-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_submission_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="boardcategory",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
