# Generated by Django 4.1.3 on 2022-12-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_board_slug_alter_boardcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
    ]
