# Generated by Django 4.1.3 on 2022-12-09 01:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_board_metric_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="metric_name",
        ),
    ]
