# Generated by Django 4.1.3 on 2022-12-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_board_metric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='metric',
            field=models.IntegerField(choices=[(0, 'Time'), (1, 'Other'), (2, 'Tears'), (3, 'Overall Time'), (4, 'Challenge Time')], default=0),
        ),
    ]
