# Generated by Django 4.1.4 on 2022-12-21 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_remove_submission_account_submission_accounts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="type",
        ),
    ]
