# Generated by Django 4.1.4 on 2022-12-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_board_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='metric_name',
            field=models.CharField(default='Time', max_length=128),
        ),
    ]
