# Generated by Django 4.1.4 on 2022-12-21 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_board_metric_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='max_team_size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
