# Generated by Django 4.1.4 on 2022-12-28 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_submission_type_alter_submission_board"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="submission",
            name="pet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="main.pet",
            ),
        ),
    ]
