# Generated by Django 4.1.4 on 2022-12-28 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0025_alter_submission_options_submission_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="main.board",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
