# Generated by Django 4.1.4 on 2022-12-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_submission_board_alter_submission_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
