# Generated by Django 4.1.4 on 2022-12-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0027_submission_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
