# Generated by Django 4.1.4 on 2023-01-04 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_alter_submission_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="submission",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
