# Generated by Django 4.1.4 on 2023-01-12 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_board_options_alter_submission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_boards', to='main.boardcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
