# Generated by Django 4.1.4 on 2023-01-12 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_populate_parentboard_20230112_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='category',
        ),
    ]
