# Generated by Django 4.1.4 on 2023-01-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_parentboard_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='icon',
        ),
    ]
