# Generated by Django 4.1.4 on 2023-01-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_parentboard_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentboard',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='board/icons/'),
        ),
    ]
