# Generated by Django 4.1.4 on 2023-01-12 04:47

from django.db import migrations


def forwards(apps, schema_data):
    board_model = apps.get_model('main', 'Board')
    parent_board_model = apps.get_model('main', 'ParentBoard')

    for parent_board in parent_board_model.objects.all():
        try:
            board = board_model.objects.get(name=parent_board.name)
        except board_model.DoesNotExist:
            continue
        parent_board.icon = board.icon
        parent_board.save()



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_parentboard_icon'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
