# Generated by Django 4.1.4 on 2023-01-12 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_board_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='max_team_size',
            new_name='team_size',
        ),
    ]
