# Generated by Django 4.1.4 on 2023-01-12 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0037_rename_max_team_size_board_team_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="parent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="main.parentboard",
            ),
            preserve_default=False,
        ),
    ]
