# Generated by Django 4.1.4 on 2023-01-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_board_options_alter_board_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='board',
            name='metric_name',
        ),
    ]
