# Generated by Django 4.1.4 on 2023-01-13 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_board_metric_remove_board_metric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
