# Generated by Django 4.1.4 on 2023-01-13 23:59
import datetime
import os
import uuid

from django.db import migrations, models


def get_file_path(instance, filename):
    ext = filename.split(".")[-1]
    return os.path.join(instance.UPLOAD_TO, f"{uuid.uuid4()}.{ext}")


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0041_alter_submission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentboard",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=get_file_path
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=get_file_path
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="submission",
            name="proof",
            field=models.ImageField(
                blank=True, null=True, upload_to=get_file_path
            ),
        ),
    ]
