# Generated by Django 4.1.4 on 2023-01-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0043_alter_submission_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="combat_achievement_tier",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "GrandMaster"), (1, "Master"), (2, "Elite")],
                default=None,
                null=True,
            ),
        ),
    ]
