# Generated by Django 4.1.4 on 2023-01-16 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_submission_combat_achievement_tier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='combat_achievement_tier',
            new_name='ca_tier',
        ),
    ]
