# Generated by Django 4.1.4 on 2023-01-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_submission_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': [models.OrderBy(models.F('date'), descending=True, nulls_last=True)]},
        ),
    ]
