# Generated by Django 4.1.4 on 2023-01-24 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_parentboard_ordering_alter_submission_ca_tier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentboard',
            options={'ordering': ['order'], 'verbose_name': 'Parent Board', 'verbose_name_plural': 'Parent Boards'},
        ),
        migrations.AddField(
            model_name='board',
            name='flex_order',
            field=models.PositiveIntegerField(blank=True, help_text='Order on leaderboard page.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='parentboard',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Order in navbar.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='parentboard',
            name='ordering',
            field=models.CharField(choices=[('-', 'Descending'), ('', 'Ascending')], default='', help_text='Order of values when showing submission from child boards.', max_length=1),
        ),
    ]
