# Generated by Django 4.1.4 on 2023-02-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_parentboard_options_alter_board_flex_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParentBoard',
            new_name='Content',
        ),
    ]
