# Generated by Django 4.1.4 on 2023-02-04 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0052_alter_content_options_alter_content_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="parent",
            new_name="content",
        ),
    ]
