# Generated by Django 4.1.4 on 2023-02-04 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_rename_parent_board_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_types', to='main.boardcategory'),
        ),
        migrations.RenameModel(
            old_name='BoardCategory',
            new_name='ContentCategory',
        ),
        migrations.AlterModelOptions(
            name='contentcategory',
            options={'verbose_name': 'Content Category', 'verbose_name_plural': 'Content Categories'},
        ),
    ]
