# Generated by Django 4.1.4 on 2023-02-08 01:19

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_account_col_logs_and_more'),
        ('main', '0055_alter_content_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(blank=True, null=True, upload_to=main.models.get_file_path)),
                ('notes', models.TextField(blank=True)),
                ('accepted', models.BooleanField(null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('date'), descending=True, nulls_last=True)],
            },
        ),
        migrations.CreateModel(
            name='RecordSubmission',
            fields=[
                ('basesubmission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basesubmission')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('accounts', models.ManyToManyField(to='account.account')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.board')),
            ],
            bases=('main.basesubmission',),
        ),
        migrations.CreateModel(
            name='PetSubmission',
            fields=[
                ('basesubmission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basesubmission')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pet')),
            ],
            bases=('main.basesubmission',),
        ),
        migrations.CreateModel(
            name='ColLogSubmission',
            fields=[
                ('basesubmission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basesubmission')),
                ('col_logs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1436)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            bases=('main.basesubmission',),
        ),
        migrations.CreateModel(
            name='CASubmission',
            fields=[
                ('basesubmission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.basesubmission')),
                ('ca_tier', models.IntegerField(blank=True, choices=[(0, 'Grandmaster'), (1, 'Master'), (2, 'Elite')], default=None, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            bases=('main.basesubmission',),
        ),
    ]
