# Generated by Django 4.1.4 on 2023-02-08 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0057_auto_20230208_0106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordsubmission",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="main.board",
            ),
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
    ]
