# Generated by Django 4.1.4 on 2023-02-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_content_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Content', 'verbose_name_plural': 'Content'},
        ),
    ]
