# Generated by Django 4.1.4 on 2023-02-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_content_options'),
        ('achievements', '0002_migrate_submissions_20230214_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casubmission',
            name='account',
        ),
        migrations.RemoveField(
            model_name='casubmission',
            name='basesubmission_ptr',
        ),
        migrations.RemoveField(
            model_name='collogsubmission',
            name='account',
        ),
        migrations.RemoveField(
            model_name='collogsubmission',
            name='basesubmission_ptr',
        ),
        migrations.RemoveField(
            model_name='petsubmission',
            name='account',
        ),
        migrations.RemoveField(
            model_name='petsubmission',
            name='basesubmission_ptr',
        ),
        migrations.RemoveField(
            model_name='petsubmission',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='recordsubmission',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='recordsubmission',
            name='basesubmission_ptr',
        ),
        migrations.RemoveField(
            model_name='recordsubmission',
            name='board',
        ),
        migrations.DeleteModel(
            name='BaseSubmission',
        ),
        migrations.DeleteModel(
            name='CASubmission',
        ),
        migrations.DeleteModel(
            name='ColLogSubmission',
        ),
        migrations.DeleteModel(
            name='PetSubmission',
        ),
        migrations.DeleteModel(
            name='RecordSubmission',
        ),
    ]
