# Generated by Django 4.1.4 on 2023-02-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0062_remove_casubmission_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="is_pb",
            field=models.BooleanField(
                default=False, verbose_name="Display on PB Leaderboards?"
            ),
        ),
    ]
