# Generated by Django 4.1.4 on 2023-02-16 22:12

from django.db import migrations

data = {
    "RECRUITER_PTS": "2",
    "RECRUITED_PTS": "0",
    "SOTM_FIRST_PTS": "3",
    "SOTM_SECOND_PTS": "2",
    "SOTM_THIRD_PTS": "1",
    "PVM_SPLITS_EASY_PTS": "0",
    "PVM_SPLITS_MEDIUM_PTS": "1",
    "PVM_SPLITS_HARD_PTS": "1",
    "PVM_SPLITS_VERY_HARD_PTS": "2",
    "MENTOR_EASY_PTS": "1",
    "MENTOR_MEDIUM_PTS": "2",
    "MENTOR_HARD_PTS": "3",
    "MENTOR_VERY_HARD_PTS": "4",
    "EVENT_MINOR_HOSTS_PTS": "5",
    "EVENT_MINOR_PARTICIPANTS_PTS": "2",
    "EVENT_MINOR_DONORS_PTS": "0",
    "EVENT_MENTOR_HOSTS_PTS": "3",
    "EVENT_MENTOR_PARTICIPANTS_PTS": "2",
    "EVENT_MENTOR_DONORS_PTS": "0",
    "EVENT_MAJOR_HOSTS_PTS": "15",
    "EVENT_MAJOR_PARTICIPANTS_PTS": "5",
    "EVENT_MAJOR_DONORS_PTS": "2",
    "EVENT_OTHER_HOSTS_PTS": "3",
    "EVENT_OTHER_PARTICIPANTS_PTS": "1",
    "EVENT_OTHER_DONORS_PTS": "0",
}

def forwards(apps, schema_data):
    settings_model = apps.get_model('main', 'Settings')
    for key, val in data.items():
        settings_model.objects.create(
            display_name=" ".join([x.title() for x in key.lower().split('_')]),
            name=key,
            value=val,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_settings_options_settings_display_name'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
