# Generated by Django 4.2.6 on 2023-11-02 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0068_umnotification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
