# Generated by Django 4.2.6 on 2023-11-29 03:27

from django.db import migrations, models
import um.functions


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0069_delete_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=um.functions.get_file_path
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=um.functions.get_file_path
            ),
        ),
    ]
