# Generated by Django 4.2.6 on 2023-12-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0073_alter_contentpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="theme",
            field=models.CharField(
                choices=[("teal", "Teal"), ("purple", "Purple"), ("brown", "Brown")],
                default="teal",
            ),
            preserve_default=False,
        ),
    ]
