# Generated by Django 4.2.6 on 2023-12-15 21:22

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0074_contentpage_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading_2", wagtail.blocks.CharBlock(max_length=128)),
                    ("heading_3", wagtail.blocks.CharBlock(max_length=128)),
                    (
                        "rich_text",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "document link",
                                "link",
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "embed",
                        wagtail.embeds.blocks.EmbedBlock(max_height=360, max_width=640),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
