# Generated by Django 4.2.8 on 2023-12-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0076_contentpage_show_page_index_alter_contentpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="logo",
            field=models.ImageField(
                default="/", help_text="Can also upload a gif.", upload_to=""
            ),
            preserve_default=False,
        ),
    ]
