# Generated by Django 4.2.8 on 2023-12-27 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0077_homepage_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="logo",
        ),
    ]
