# Generated by Django 4.2.8 on 2023-12-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("main", "0078_remove_homepage_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="logo",
            field=models.ForeignKey(
                help_text="Upload an image/gif to display on the home page of the website.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
