# Generated by Django 4.2.8 on 2023-12-28 17:51

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0080_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "theme",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("teal", "Teal"),
                                            ("purple", "Purple"),
                                            ("brown", "Brown"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock()),
                                ("description", wagtail.blocks.TextBlock()),
                                ("link", wagtail.blocks.PageChooserBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
