# Generated by Django 4.2.6 on 2024-01-17 02:53

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0082_alter_contentpage_theme_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading_2", wagtail.blocks.CharBlock(max_length=128)),
                    ("heading_3", wagtail.blocks.CharBlock(max_length=128)),
                    (
                        "rich_text",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "document link",
                                "link",
                                "image",
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "embed",
                        wagtail.embeds.blocks.EmbedBlock(max_height=540, max_width=960),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "banner",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "theme",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("green", "Green"),
                                            ("purple", "Purple"),
                                            ("brown", "Brown"),
                                        ]
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.RichTextBlock(features=["image"]),
                                ),
                                ("description", wagtail.blocks.TextBlock()),
                                ("link", wagtail.blocks.PageChooserBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
