# Generated by Django 4.2.9 on 2024-01-17 17:26

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0083_alter_contentpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading_2", wagtail.blocks.CharBlock(max_length=128)),
                    ("heading_3", wagtail.blocks.CharBlock(max_length=128)),
                    (
                        "rich_text",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "document link",
                                "link",
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "embed",
                        wagtail.embeds.blocks.EmbedBlock(max_height=540, max_width=960),
                    ),
                    (
                        "emoji_row",
                        wagtail.blocks.StructBlock(
                            [
                                ("emoji", wagtail.images.blocks.ImageChooserBlock()),
                                ("text", wagtail.blocks.TextBlock()),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
