# Generated by Django 4.2.9 on 2024-01-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0084_alter_contentpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="author",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
