# Generated by Django 4.2.9 on 2024-01-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0085_contentpage_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="author",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to automatically show authors as all users who have edited this page.",
                max_length=64,
            ),
        ),
    ]
