# Generated by Django 4.2.9 on 2024-01-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0086_alter_contentpage_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
