# Generated by Django 4.2.9 on 2024-01-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0088_populate_board_slug_20240125_1916"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
