# Generated by Django 4.2.9 on 2024-01-25 19:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0089_alter_board_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="flex_order",
        ),
    ]
