# Generated by Django 4.2.9 on 2024-01-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0090_remove_board_flex_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="board",
            name="slug",
            field=models.SlugField(),
        ),
    ]
