# Generated by Django 4.2.9 on 2024-01-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0091_alter_board_name_alter_board_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="hiscores_name",
            field=models.CharField(
                default="",
                help_text="The name of this content on the official OSRS Hiscores page. Must match exactly what is on the hiscores page, case insensitive.",
                max_length=256,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="content",
            name="name",
            field=models.CharField(
                help_text="Display name for this content on the website.",
                max_length=256,
                unique=True,
            ),
        ),
    ]
