# Generated by Django 4.2.9 on 2024-01-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0093_auto_20240126_1743"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="hiscores_name",
            field=models.CharField(
                help_text="The name of this content on the official OSRS Hiscores page. Must match exactly what is on the hiscores page.",
                max_length=256,
                unique=True,
            ),
        ),
    ]
