# Generated by Django 4.2.9 on 2024-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0094_alter_content_hiscores_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="has_hiscores",
            field=models.BooleanField(
                default=True,
                verbose_name="Check if this content has a corresponding page on the official OSRS hiscores page.",
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="hiscores_name",
            field=models.CharField(
                blank=True,
                help_text="The name of this content on the official OSRS Hiscores page. Must match exactly what is on the hiscores page, case insensitive.",
                max_length=256,
                unique=True,
            ),
        ),
    ]
