# Generated by Django 4.2.9 on 2024-01-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0095_content_has_hiscores_alter_content_hiscores_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="hiscores_name",
            field=models.CharField(
                blank=True,
                help_text="The name of this content on the official OSRS Hiscores page. Must match exactly what is on the hiscores page, case insensitive.",
                max_length=256,
            ),
        ),
    ]
