# Generated by Django 4.2.9 on 2024-01-28 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0096_alter_content_hiscores_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="main.contentcategory",
            ),
        ),
    ]
