# Generated by Django 4.2.9 on 2024-02-02 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0097_alter_content_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="points_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Multiplier for points earned from this board.",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
