# Generated by Django 4.2.9 on 2024-02-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0098_board_points_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="display_board",
            field=models.BooleanField(default=True),
        ),
    ]
