# Generated by Django 4.2.9 on 2024-02-05 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0099_board_display_board"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="display_board",
            new_name="is_active",
        ),
    ]
