# Generated by Django 4.2.9 on 2024-02-05 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0100_rename_display_board_board_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="is_pb",
            new_name="has_pbs",
        ),
    ]
