# Generated by Django 4.2.9 on 2024-02-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0101_rename_is_pb_content_has_pbs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="can_be_mentored",
            field=models.BooleanField(default=False, verbose_name="Can be mentored."),
        ),
        migrations.AlterField(
            model_name="content",
            name="can_be_split",
            field=models.BooleanField(default=False, verbose_name="Can be split."),
        ),
        migrations.AlterField(
            model_name="content",
            name="has_hiscores",
            field=models.BooleanField(
                default=True, verbose_name="Has official OSRS hiscores."
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="has_pbs",
            field=models.BooleanField(
                default=False, verbose_name="Has personal bests."
            ),
        ),
    ]
