# Generated by Django 4.2.9 on 2024-04-08 18:46

from django.db import migrations
import main.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0102_alter_content_can_be_mentored_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading_2", wagtail.blocks.CharBlock(max_length=128)),
                    ("heading_3", wagtail.blocks.CharBlock(max_length=128)),
                    (
                        "rich_text",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "document link",
                                "link",
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("embed", main.blocks.EmbedBlock()),
                    (
                        "emoji_row",
                        wagtail.blocks.StructBlock(
                            [
                                ("emoji", wagtail.images.blocks.ImageChooserBlock()),
                                ("text", wagtail.blocks.TextBlock()),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
