# Generated by Django 4.2.9 on 2024-07-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0103_alter_contentpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=256, unique=True)),
                ("value", models.CharField(max_length=256)),
            ],
        ),
    ]
