# Generated by Django 4.2.9 on 2024-07-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0105_populate_settings_20240722_1842"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="settings",
            options={"verbose_name": "Settings", "verbose_name_plural": "Settings"},
        ),
        migrations.AlterField(
            model_name="settings",
            name="value",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
