# Generated by Django 4.2.24 on 2025-09-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0106_alter_settings_options_alter_settings_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="metric",
            field=models.IntegerField(
                choices=[(0, "Time"), (1, "Integer"), (2, "Decimal")], default=0
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="metric_name",
            field=models.CharField(default="Time", max_length=128),
        ),
    ]
