# Generated by Django 4.2.24 on 2025-09-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0108_auto_20250929_1911"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="metric",
        ),
        migrations.RemoveField(
            model_name="content",
            name="metric_name",
        ),
    ]
