# Generated by Django 5.2.6 on 2026-02-25 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0109_remove_content_metric_remove_content_metric_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"ordering": ["order", "team_size", "name"]},
        ),
        migrations.AddField(
            model_name="board",
            name="order",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Order displayed on leadboard page. Empty values will appear last (order is then defined by team size and alphabetical order of name). Allowed numbers are 1 - 12.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
    ]
