# Generated by Django 5.2.12 on 2026-07-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0110_alter_board_options_board_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="submissions_ordering",
            field=models.CharField(
                choices=[("-", "Descending"), ("", "Ascending")],
                default="",
                help_text="Order of values when showing submissions.",
                max_length=1,
            ),
        ),
    ]
