# Generated by Django 5.2.12 on 2026-07-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0112_auto_20260706_1719"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="ordering",
        ),
    ]
