# Generated by Django 5.2.12 on 2026-09-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0113_remove_content_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="submissions_ordering",
            field=models.CharField(
                blank=True,
                choices=[("-", "Descending"), ("", "Ascending")],
                default="",
                help_text="Order of values when showing submissions.",
                max_length=1,
            ),
        ),
    ]
